#!/bin/sh

# add new driver
/sbin/insmod /usr/local/daq/aes-stream-drivers/data_dev/driver/datadev.ko cfgSize=2097152 cfgRxCount=32 cfgTxCount=16 || exit 1

# give appropriate group/permissions
chmod 666 /dev/datadev*
