lztsBoard:
  enable: 'True'
  forceWrite: 'False'
  dataWriter:
    enable: 'True'
    dataFile: ''
    open: 'False'
    bufferSize: '0'
    maxFileSize: '0'
  Lzts:
    enable: 'True'
    AxiVersion:
      enable: 'True'
      ScratchPad: '0x0'
      FpgaReloadHalt: '0x0'
      FpgaReload: '0x0'
      FpgaReloadAddress: '0x0'
    LztsPowerRegisters:
      enable: 'True'
      EnDcDcAm6V: 'True'
      EnDcDcAp5V4: 'False'
      EnDcDcAp3V7: 'True'
      EnDcDcAp2V3: 'True'
      EnDcDcAp1V6: 'False'
      EnLdoSlow: 'True'
      EnLdoFast: 'False'
      EnLdoAm5V: 'True'
      Led0: 'True'
      Led1: 'False'
      Led2: 'True'
      Led3: 'False'
      SADCRst: '0x0'
      SADCCtrl1: '0x0'
      SADCCtrl2: '0x0'
      SAMPEn: '0xf'
      FADCPdn: '0xf'
      DcDcSyncAll: 'False'
      DcDcHalfClkAp6V: '0x0'
      DcDcHalfClkAm6V: '0x0'
      DcDcHalfClkAp5V4: '0x0'
      DcDcHalfClkAp3V7: '0x0'
      DcDcHalfClkAp2V3: '0x0'
      DcDcHalfClkAp1V6: '0x0'
      DcDcHalfClkDp6V: '0x0'
      DcDcHalfClkDp3V3: '0x0'
      DcDcHalfClkDp1V8: '0x0'
      DcDcHalfClkDp1V2: '0x0'
      DcDcHalfClkDp0V95: '0x0'
      DcDcHalfClkMgt1V0: '0x0'
      DcDcHalfClkMgt1V2: '0x0'
      DcDcHalfClkMgt1V8: '0x0'
      DcDcPhaseAp6V: '0x0'
      DcDcPhaseAm6V: '0x0'
      DcDcPhaseAp5V4: '0x0'
      DcDcPhaseAp3V7: '0x0'
      DcDcPhaseAp2V3: '0x0'
      DcDcPhaseAp1V6: '0x0'
      DcDcPhaseDp6V: '0x0'
      DcDcPhaseDp3V3: '0x0'
      DcDcPhaseDp1V8: '0x0'
      DcDcPhaseDp1V2: '0x0'
      DcDcPhaseDp0V95: '0x0'
      DcDcPhaseMgt1V0: '0x0'
      DcDcPhaseMgt1V2: '0x0'
      DcDcPhaseMgt1V8: '0x0'
    Pgp2bAxi:
      enable: 'True'
      Loopback: '0x0'
      LocData: '0x0'
      LocDataEn: 'False'
      AutoStatus: 'False'
    SlowAdcConfig0:
      enable: 'False'
      AdcReg_0x0006: '0x0'
      AdcReg_0x0007: '0x0'
      AdcReg_0x0008: '0x0'
      AdcReg_0x000B: '0x0'
      AdcReg_0x000C: '0x0'
      AdcReg_0x000D: '0x0'
      AdcReg_0x000F: '0x0'
      AdcReg_0x0010: '0x0'
      AdcReg_0x0011: '0x0'
      AdcReg_0x0012: '0x0'
      AdcReg_0x0013: '0x0'
      AdcReg_0x0014: '0x0'
      AdcReg_0x0015: '0x0'
      AdcReg_0x0016: '0x0'
      AdcReg_0x0017: '0x0'
      AdcReg_0x0018: '0x0'
      AdcReg_0x001F: '0x0'
      AdcReg_0x0020: '0x0'
    SlowAdcConfig1:
      enable: 'False'
      AdcReg_0x0006: '0x0'
      AdcReg_0x0007: '0x0'
      AdcReg_0x0008: '0x0'
      AdcReg_0x000B: '0x0'
      AdcReg_0x000C: '0x0'
      AdcReg_0x000D: '0x0'
      AdcReg_0x000F: '0x0'
      AdcReg_0x0010: '0x0'
      AdcReg_0x0011: '0x0'
      AdcReg_0x0012: '0x0'
      AdcReg_0x0013: '0x0'
      AdcReg_0x0014: '0x0'
      AdcReg_0x0015: '0x0'
      AdcReg_0x0016: '0x0'
      AdcReg_0x0017: '0x0'
      AdcReg_0x0018: '0x0'
      AdcReg_0x001F: '0x0'
      AdcReg_0x0020: '0x0'
    SlowAdcConfig2:
      enable: 'False'
      AdcReg_0x0006: '0x0'
      AdcReg_0x0007: '0x0'
      AdcReg_0x0008: '0x0'
      AdcReg_0x000B: '0x0'
      AdcReg_0x000C: '0x0'
      AdcReg_0x000D: '0x0'
      AdcReg_0x000F: '0x0'
      AdcReg_0x0010: '0x0'
      AdcReg_0x0011: '0x0'
      AdcReg_0x0012: '0x0'
      AdcReg_0x0013: '0x0'
      AdcReg_0x0014: '0x0'
      AdcReg_0x0015: '0x0'
      AdcReg_0x0016: '0x0'
      AdcReg_0x0017: '0x0'
      AdcReg_0x0018: '0x0'
      AdcReg_0x001F: '0x0'
      AdcReg_0x0020: '0x0'
    SlowAdcConfig3:
      enable: 'False'
      AdcReg_0x0006: '0x0'
      AdcReg_0x0007: '0x0'
      AdcReg_0x0008: '0x0'
      AdcReg_0x000B: '0x0'
      AdcReg_0x000C: '0x0'
      AdcReg_0x000D: '0x0'
      AdcReg_0x000F: '0x0'
      AdcReg_0x0010: '0x0'
      AdcReg_0x0011: '0x0'
      AdcReg_0x0012: '0x0'
      AdcReg_0x0013: '0x0'
      AdcReg_0x0014: '0x0'
      AdcReg_0x0015: '0x0'
      AdcReg_0x0016: '0x0'
      AdcReg_0x0017: '0x0'
      AdcReg_0x0018: '0x0'
      AdcReg_0x001F: '0x0'
      AdcReg_0x0020: '0x0'
    SlowAdcReadout0:
      enable: 'False'
      DelayAdcALane[0]: '0x0'
      DelayAdcALane[1]: '0x0'
      DelayAdcALane[2]: '0x0'
      DelayAdcALane[3]: '0x0'
      DelayAdcALane[4]: '0x0'
      DelayAdcALane[5]: '0x0'
      DelayAdcALane[6]: '0x0'
      DelayAdcALane[7]: '0x0'
      DelayAdcBLane[0]: '0x0'
      DelayAdcBLane[1]: '0x0'
      DelayAdcBLane[2]: '0x0'
      DelayAdcBLane[3]: '0x0'
      DelayAdcBLane[4]: '0x0'
      DelayAdcBLane[5]: '0x0'
      DelayAdcBLane[6]: '0x0'
      DelayAdcBLane[7]: '0x0'
      DMode: '0x0'
      Invert: '0x0'
      Convert: '0x0'
    SlowAdcReadout1:
      enable: 'False'
      DelayAdcALane[0]: '0x0'
      DelayAdcALane[1]: '0x0'
      DelayAdcALane[2]: '0x0'
      DelayAdcALane[3]: '0x0'
      DelayAdcALane[4]: '0x0'
      DelayAdcALane[5]: '0x0'
      DelayAdcALane[6]: '0x0'
      DelayAdcALane[7]: '0x0'
      DelayAdcBLane[0]: '0x0'
      DelayAdcBLane[1]: '0x0'
      DelayAdcBLane[2]: '0x0'
      DelayAdcBLane[3]: '0x0'
      DelayAdcBLane[4]: '0x0'
      DelayAdcBLane[5]: '0x0'
      DelayAdcBLane[6]: '0x0'
      DelayAdcBLane[7]: '0x0'
      DMode: '0x0'
      Invert: '0x0'
      Convert: '0x0'
    SlowAdcReadout2:
      enable: 'False'
      DelayAdcALane[0]: '0x0'
      DelayAdcALane[1]: '0x0'
      DelayAdcALane[2]: '0x0'
      DelayAdcALane[3]: '0x0'
      DelayAdcALane[4]: '0x0'
      DelayAdcALane[5]: '0x0'
      DelayAdcALane[6]: '0x0'
      DelayAdcALane[7]: '0x0'
      DelayAdcBLane[0]: '0x0'
      DelayAdcBLane[1]: '0x0'
      DelayAdcBLane[2]: '0x0'
      DelayAdcBLane[3]: '0x0'
      DelayAdcBLane[4]: '0x0'
      DelayAdcBLane[5]: '0x0'
      DelayAdcBLane[6]: '0x0'
      DelayAdcBLane[7]: '0x0'
      DMode: '0x0'
      Invert: '0x0'
      Convert: '0x0'
    SlowAdcReadout3:
      enable: 'False'
      DelayAdcALane[0]: '0x0'
      DelayAdcALane[1]: '0x0'
      DelayAdcALane[2]: '0x0'
      DelayAdcALane[3]: '0x0'
      DelayAdcALane[4]: '0x0'
      DelayAdcALane[5]: '0x0'
      DelayAdcALane[6]: '0x0'
      DelayAdcALane[7]: '0x0'
      DelayAdcBLane[0]: '0x0'
      DelayAdcBLane[1]: '0x0'
      DelayAdcBLane[2]: '0x0'
      DelayAdcBLane[3]: '0x0'
      DelayAdcBLane[4]: '0x0'
      DelayAdcBLane[5]: '0x0'
      DelayAdcBLane[6]: '0x0'
      DelayAdcBLane[7]: '0x0'
      DMode: '0x0'
      Invert: '0x0'
      Convert: '0x0'
    SadcBufferWriter0:
      enable: 'True'
      Enable: 'True'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter1:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter2:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter3:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter4:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter5:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter6:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferWriter7:
      enable: 'True'
      Enable: 'False'
      IntPreThreshold: '0x0'
      IntPostThreshold: '0x0'
      IntVetoThreshold: '0x0'
      IntPreDelay: '0x0'
      IntPostDelay: '0x0'
      ExtTrigSize: '0x4000'
    SadcBufferReader:
      enable: 'False'
    SadcPatternTester:
      enable: 'False'
      Channel: '0x0'
      Mask: '0x0'
      Pattern: '0x0'
      Samples: '0x0'
      Request: 'False'
  runControl:
    enable: 'True'
    runState: Stopped
    runRate: 1 Hz
    runCount: '0'
